repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Lint and format Python files using ruff.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      # Run the linter.
      - id: ruff-check
        args: ["--fix"]
        language: system
        types: [python]
        files: (litellm/|litellm_proxy_extras/|enterprise/).*\.py
        exclude: ^litellm/__init__.py$
      # Run the formatter.
      - id: ruff-format
        language: system
        types: [python]
        files: (litellm/|litellm_proxy_extras/|enterprise/).*\.py
        exclude: ^litellm/__init__.py$
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
        files: ^(pyproject.toml|litellm-proxy-extras/pyproject.toml)$
